# MTJ Build Properties
Regular.includes=src\
,res\
,j2mekeyboard/res\

Regular.excludes=\

Lite.includes=src\
,res\
,res/l/en\

Lite.excludes=j2mekeyboard\
,res/c\
,res/i\
,res/m.svg\
,res/gr.png\
,res/us.png\
,res/folder.png\
,res/file.png\
,res/l\
,res/msg.mid\

BlackBerry.includes=src\
,res\
,j2mekeyboard/res\

BlackBerry.excludes=res/m.svg\

OnDeviceDebug.includes=src\
,res\
,j2mekeyboard/res\

OnDeviceDebug.excludes=\

