from os import listdir
import json

def load_jsonc(f):
    cleaned=""
    for s in f:
        if s.strip().startswith("//"):
            continue
        if " // " in s:
            cleaned += s[:s.index(" // ")]
        else:
            cleaned += s
    return json.loads(cleaned)

desc=[]
with open("en.jsonc", encoding="utf-8") as f:
    desc = load_jsonc(f)

with open("../src/LangConstants.java", "w") as f:
    f.write("/* DO NOT EDIT THIS FILE - it is machine generated */\n")
    f.write("\n")
    f.write("public interface LangConstants {\n")
    i = 1
    for s in desc:
        f.write("\tstatic final int " + s + " = " + str(i) + ";\n")
        i += 1
    f.write("\tstatic final int mpgram = 0;\n")
    f.write("}\n")

for n in listdir():
    if not n.endswith(".jsonc"):
        continue
    print(n)
    
    j = None
    with open(n, encoding="utf-8") as f:
        j = load_jsonc(f)

    with open("../res/l/" + n[:-6], mode='w', encoding="utf-8") as f:
        for s in desc.keys():
            if s in j:
                f.write(j[s].replace("\n", "\\\n"))
            else:
                f.write(desc[s].replace("\n", "\\\n"))
                print(s, "missing")
            f.write("\n")
